function createfigure(X1, Y1, X2, Y2, X3, Y3, X4, Y4, X5, Y5, X6, Y6, X7, Y7, X8, Y8, X9, Y9, X10, Y10, X11, Y11, X12, Y12, X13, Y13, X14, Y14, X15, Y15, X16, Y16, X17, Y17, X18, Y18, X19, Y19, X20, Y20, X21, Y21, X22, Y22, X23, Y23, X24, Y24, X25, Y25, X26, Y26, X27, Y27, X28, Y28, X29, Y29, X30, Y30, X31, Y31, X32, Y32, X33, Y33, X34, Y34, X35, Y35, X36, Y36, X37, Y37, X38, Y38, X39, Y39, X40, Y40, X41, Y41, X42, Y42, X43)
%CREATEFIGURE(X1, Y1, X2, Y2, X3, Y3, X4, Y4, X5, Y5, X6, Y6, X7, Y7, X8, Y8, X9, Y9, X10, Y10, X11, Y11, X12, Y12, X13, Y13, X14, Y14, X15, Y15, X16, Y16, X17, Y17, X18, Y18, X19, Y19, X20, Y20, X21, Y21, X22, Y22, X23, Y23, X24, Y24, X25, Y25, X26, Y26, X27, Y27, X28, Y28, X29, Y29, X30, Y30, X31, Y31, X32, Y32, X33, Y33, X34, Y34, X35, Y35, X36, Y36, X37, Y37, X38, Y38, X39, Y39, X40, Y40, X41, Y41, X42, Y42, X43)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data
%  X3:  vector of x data
%  Y3:  vector of y data
%  X4:  vector of x data
%  Y4:  vector of y data
%  X5:  vector of x data
%  Y5:  vector of y data
%  X6:  vector of x data
%  Y6:  vector of y data
%  X7:  vector of x data
%  Y7:  vector of y data
%  X8:  vector of x data
%  Y8:  vector of y data
%  X9:  vector of x data
%  Y9:  vector of y data
%  X10:  vector of x data
%  Y10:  vector of y data
%  X11:  vector of x data
%  Y11:  vector of y data
%  X12:  vector of x data
%  Y12:  vector of y data
%  X13:  vector of x data
%  Y13:  vector of y data
%  X14:  vector of x data
%  Y14:  vector of y data
%  X15:  vector of x data
%  Y15:  vector of y data
%  X16:  vector of x data
%  Y16:  vector of y data
%  X17:  vector of x data
%  Y17:  vector of y data
%  X18:  vector of x data
%  Y18:  vector of y data
%  X19:  vector of x data
%  Y19:  vector of y data
%  X20:  vector of x data
%  Y20:  vector of y data
%  X21:  vector of x data
%  Y21:  vector of y data
%  X22:  vector of x data
%  Y22:  vector of y data
%  X23:  vector of x data
%  Y23:  vector of y data
%  X24:  vector of x data
%  Y24:  vector of y data
%  X25:  vector of x data
%  Y25:  vector of y data
%  X26:  vector of x data
%  Y26:  vector of y data
%  X27:  vector of x data
%  Y27:  vector of y data
%  X28:  vector of x data
%  Y28:  vector of y data
%  X29:  vector of x data
%  Y29:  vector of y data
%  X30:  vector of x data
%  Y30:  vector of y data
%  X31:  vector of x data
%  Y31:  vector of y data
%  X32:  vector of x data
%  Y32:  vector of y data
%  X33:  vector of x data
%  Y33:  vector of y data
%  X34:  vector of x data
%  Y34:  vector of y data
%  X35:  vector of x data
%  Y35:  vector of y data
%  X36:  vector of x data
%  Y36:  vector of y data
%  X37:  vector of x data
%  Y37:  vector of y data
%  X38:  vector of x data
%  Y38:  vector of y data
%  X39:  vector of x data
%  Y39:  vector of y data
%  X40:  vector of x data
%  Y40:  vector of y data
%  X41:  vector of x data
%  Y41:  vector of y data
%  X42:  vector of x data
%  Y42:  vector of y data
%  X43:  vector of x data

%  Auto-generated by MATLAB on 08-Jun-2021 19:33:37

% Create figure
figure1 = figure('WindowState','maximized','NumberTitle','off',...
    'Name','Figure',...
    'Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'Color',[0 0 0]);

% Create plot
plot(X2,Y2,'Color',[0 0 0]);

% Create plot
plot(X3,Y3,'Color',[0 0 0]);

% Create plot
plot(X4,Y4,'Color',[0 0 0]);

% Create plot
plot(X5,Y5,'Color',[0 0 0]);

% Create plot
plot(X6,Y6,'Color',[0 0 0]);

% Create plot
plot(X7,Y7,'Color',[0 0 0]);

% Create plot
plot(X8,Y8,'Color',[0 0 0]);

% Create plot
plot(X9,Y9,'Color',[0 0 0]);

% Create plot
plot(X10,Y10,'Color',[0 0 0]);

% Create plot
plot(X11,Y11,'Color',[0 0 0]);

% Create plot
plot(X12,Y12,'Color',[0 0 0]);

% Create plot
plot(X13,Y13,'Color',[0 0 0]);

% Create plot
plot(X14,Y14,'Color',[0 0 0]);

% Create plot
plot(X15,Y15,'Color',[0 0 0]);

% Create plot
plot(X16,Y16,'Color',[0 0 0]);

% Create plot
plot(X17,Y17,'Color',[0 0 0]);

% Create plot
plot(X18,Y18,'Color',[0 0 0]);

% Create plot
plot(X19,Y19,'Color',[0 0 0]);

% Create plot
plot(X20,Y20,'Color',[0 0 0]);

% Create plot
plot(X21,Y21,'Color',[0 0 0]);

% Create plot
plot(X22,Y22,'Color',[0 0 0]);

% Create plot
plot(X23,Y23,'Color',[0 0 0]);

% Create plot
plot(X24,Y24,'Color',[0 0 0]);

% Create plot
plot(X25,Y25,'Color',[0 0 0]);

% Create plot
plot(X26,Y26,'Color',[0 0 0]);

% Create plot
plot(X27,Y27,'Color',[0 0 0]);

% Create plot
plot(X28,Y28,'Color',[0 0 0]);

% Create plot
plot(X29,Y29,'Color',[0 0 0]);

% Create plot
plot(X30,Y30,'Color',[0 0 0]);

% Create plot
plot(X31,Y31,'Color',[0 0 0]);

% Create plot
plot(X32,Y32,'Color',[0 0 0]);

% Create plot
plot(X33,Y33,'Color',[0 0 0]);

% Create plot
plot(X34,Y34,'Color',[0 0 0]);

% Create plot
plot(X35,Y35,'Color',[0 0 0]);

% Create plot
plot(X36,Y36,'Color',[0 0 0]);

% Create plot
plot(X37,Y37,'Color',[0 0 0]);

% Create plot
plot(X38,Y38,'Color',[0 0 0]);

% Create plot
plot(X39,Y39,'Color',[0 0 0]);

% Create plot
plot(X40,Y40,'Color',[0 0 0]);

% Create plot
plot(X41,Y41,'Color',[0 0 0]);

% Create plot
plot(X42,Y42,'Marker','+','LineWidth',3,'LineStyle','none',...
    'Color',[0.5 0 0]);

% Create plot
plot(X43,Y42,'Marker','+','LineWidth',3,'LineStyle','none',...
    'Color',[0.5 0 0]);

% Create plot
plot(Y42,Y42,'Marker','*','LineWidth',3,'LineStyle','none',...
    'Color',[0 0.5 0]);

% Create ylabel
ylabel('x_2');

% Create xlabel
xlabel('x_1');

grid(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'ContextMenu');
% Create ellipse
annotation(figure1,'ellipse',...
    [0.331729166666667 0.304213771839672 0.370875 0.421377183967112],...
    'Color',[0 0.447058823529412 0.741176470588235]);

